spring:
  kafka:
#    bootstrap-servers:

    producer:
      key-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer

    consumer:
#      group-id:
#      auto-offset-reset: earliest
      key-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer

    # Additional properties, common to producers and consumers, used to configure the client
    properties:
      schema:
        registry:
          url: http://localhost:8081
      specific:
        avro:
          reader: true

#      security:
#        protocol: SASL_SSL
#      sasl:
#        jaas:
#          config: org.apache.kafka.common.security.plain.PlainLoginModule required username='' password='';
#        mechanism: PLAIN